baseURL = 'https://mrmateussiilva.github.io/'
languageCode = "pt-br"
title = "O Código e  o Bug"
theme = "hugo-bearblog"

# Configuração para corrigir links quebrados no GitHub Pages
relativeURLs = true
uglyURLs = true

[params]
  description = "Um blog criado com Hugo e publicado no GitHub Pages."

[menu]
 
  [[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 2